### PR TITLE
#517 AccountDeleteIT

### LINKED ISSUE #517: Create ITs for AccountDelete

### PR DESCRIPTION
**Pull request by agutierrez0**
Added integration tests for `AccountDelete` transaction. Closes #517 

- Covered all error cases except `tefTOO_BIG`, object submitted to the ledger would have been the same as other tests so wanted to avoid "testing the ledger" vs "testing `AccountDelete`".
- Moved `getMinExpirationTime` function into `AbstractIT` as I used it when creating an `EscrowCreate` transaction for the `finishAfter` parameter.
- Used `DisabledIf` annotation to only run successful test on local rippled nodes, this was because `AccountDelete` requires 256 ledgers to pass before being working successfully and I was using an `XrplAdminClient` instance to accept the ledgers.
- Exposed new method `acceptLedger` in `RippleDContainer`/`LocalRippledEnvironment` in order to accept ledger at the speed of code compared to the interval speed we set for `LEDGER_ACCEPTOR`.

First time contributing to open source code, open to any feedback 👍🏽

### CODE REVIEW

**Review by sappenin — APPROVED** [review]
LGTM, thanks for the submission, and happy to have you contributing @agutierrez0 !!

**Review by sappenin — CHANGES_REQUESTED** [review]
Oops, I spoke too soon -- looks like there's a checkstyle issue in the build. Here's the error:

```
[WARN] /home/runner/work/xrpl4j/xrpl4j/xrpl4j-integration-tests/src/test/java/org/xrpl/xrpl4j/tests/AccountDeleteIT.java:278:5: Distance between
 variable 'receiverAccount' declaration and its first usage is 4, but allowed 3.  Consider
 making that variable final if you still need to store its value in advance (before method 
calls that might have side effects on the original value).
[VariableDeclarationUsageDistance]
```

**Comment by agutierrez0** [comment]
> Oops, I spoke too soon -- looks like there's a checkstyle issue in the build. Here's the error:
> 
> ```
> [WARN] /home/runner/work/xrpl4j/xrpl4j/xrpl4j-integration-tests/src/test/java/org/xrpl/xrpl4j/tests/AccountDeleteIT.java:278:5: Distance between
>  variable 'receiverAccount' declaration and its first usage is 4, but allowed 3.  Consider
>  making that variable final if you still need to store its value in advance (before method 
> calls that might have side effects on the original value).
> [VariableDeclarationUsageDistance]
> ```

@sappenin Hmm yeah I saw this error too earlier and pushed this commit to address it: https://github.com/XRPLF/xrpl4j/pull/568/commits/ee7029d67157b4401e07c0ebe2125e7b2a00fa67

I'm not seeing any of the jobs fail and I am not able to reproduce the error when building locally, is there any way I could see which job threw the error? Not sure how to "re-run" the pipeline like how we do with GitLab 😅 

Thanks for taking the time to review

**Comment by sappenin** [comment]
Sure thing - you can see the jobs that get run [here](https://github.com/XRPLF/xrpl4j/actions) (see `Actions` tab above). I've kicked off another build to see what happens.

**Comment by agutierrez0** [comment]
Thanks for rerunning @sappenin, just made one more change https://github.com/XRPLF/xrpl4j/pull/568/commits/1b17c553f1e22275ce280fd84099324013fb34dc moving that `receiverAccount` variable down. i saw the error message suggest making it `final` and gave that a shot, but went with moving it down instead. updated comments as well. 

will my pushes automatically trigger another build?

**Comment by sappenin** [comment]
Sorry @agutierrez0, I missed this one -- just triggered a new build (see [here](https://github.com/XRPLF/xrpl4j/actions/runs/11667039689)).

**Comment by agutierrez0** [comment]
No problem & thanks @sappenin 👍🏽 , i see my build failed again but it has to do with `PaymentChannelIT`. Could my changes have somehow impacted those integration tests?

**Comment by sappenin** [comment]
> i see my build failed again but it has to do with `PaymentChannelIT`. Could my changes have somehow impacted those integration tests?

Unclear, seems unlikely. I've kicked-off another build, so let's see what happens. 

I presume all ITs pass locally?

**Review by nkramer44 — APPROVED** [review]

**Comment by agutierrez0** [comment]
thanks for the approve @nkramer44 👍🏽 

i see that the build continues to fail. locally the ITs pass:

image

is there anything i can do to address the issues in the pipeline build?

**Comment by sappenin** [comment]
@agutierrez0 It seems like the broken build isn't due to your changes, so I'm going to merge now and let's see what happens to the build on `main`. For now, it's mostly working (see [here](https://github.com/XRPLF/xrpl4j/actions/runs/11807191637/job/32893376283)), so let's see what happens.

**Review by sappenin — APPROVED** [review]

**Comment by agutierrez0** [comment]
@sappenin , thanks for the help triaging this. @nkramer44 let me know that the `@DisabledIf` annotation might not be working as expected since it looks like tests are running on testnet and devnet, and since I am doing this manual accepting of the ledger, it might be erroring out there.

I noticed everywhere else `@DisabledIf` was being used, it was for the entire class, so I moved mine to be for the entire class as well. Would you mind running another build to see if this could address the issue?

**Comment by sappenin** [comment]
> Would you mind running another build to see if this could address the issue?

Sure thing - just approved it.

**Pull request merged**
