### PR TITLE
Fix 529: Make all AMM transaction IssuedCurrencyAmount fields CurrencyAmounts

### LINKED ISSUE #529: `AmmBid` expects BidMax to be of type `IssuedCurrencyAmount` but it can be a string
The current JSON deserializer expects `BidMax` to be of `IssuedCurrencyAmount`, however, as observed on mainnet, this is not always the case:

https://xrpscan.com/ledger/BAA4AF508E9A9CB7685D9E61B82486681E52E9B920904B0650499497F050D8FA
Tx https://xrpscan.com/tx/6A8BC948E1309219EA8E14905D0EA9BB94E24429DE5B15CDE8916CDBCE42034B provides a string value of "10"

### PR DESCRIPTION
**Pull request by nkramer44**
Fixes #529 by retyping all `IssuedCurrencyAmount`s in AMM related transactions to `CurrencyAmounts`.

This does not constitute a breaking change, because these transactions were marked `@Beta`.

### CODE REVIEW

**Review by sappenin — APPROVED** [review]
LGTM!

**Comment by nkramer44** [comment]
> Any idea when this PR will be fixed & a release cut?

@exp0nge We're planning on merging this and releasing a fix version some time this week or early next (this week is Apex)

**Comment by abhaar-gemini** [comment]
@nkramer44 Any updates on releasing a patched version with this fix?

**Comment by sappenin** [comment]
Hi @abhaar-gemini and @exp0nge -- see https://github.com/XRPLF/xrpl4j/releases/tag/v3.3.1 and let us know if you run into any issues.

**Pull request merged**
